import { FormEvent, useEffect, useMemo, useState } from "react";
import "./App.css";

type Page = "dashboard" | "projects" | "projectDetails" | "tasks" | "calendar" | "team" | "reports" | "activity" | "settings";
type ProjectStatus = "Planning" | "Not Started" | "In Progress" | "On Hold" | "Completed" | "Cancelled";
type TaskStatus = "To Do" | "In Progress" | "Review" | "Completed";
type Priority = "Low" | "Medium" | "High" | "Critical";
type Role = "Admin" | "Project Manager" | "Developer" | "Designer" | "Tester" | "Member";

interface User { id: string; name: string; email: string; role: Role; password?: string; }
interface TeamMember { id: string; name: string; email: string; role: Role; }
interface Project { id: string; name: string; description: string; managerId: string; teamIds: string[]; startDate: string; dueDate: string; priority: Priority; status: ProjectStatus; }
interface Task { id: string; title: string; description: string; projectId: string; assignedTo: string; priority: Priority; status: TaskStatus; startDate: string; dueDate: string; createdAt: string; }
interface Activity { id: string; action: string; user: string; createdAt: string; }

const PROJECT_STATUSES: ProjectStatus[] = ["Planning", "Not Started", "In Progress", "On Hold", "Completed", "Cancelled"];
const TASK_STATUSES: TaskStatus[] = ["To Do", "In Progress", "Review", "Completed"];
const PRIORITIES: Priority[] = ["Low", "Medium", "High", "Critical"];
const ROLES: Role[] = ["Admin", "Project Manager", "Developer", "Designer", "Tester", "Member"];

const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const today = () => new Date().toISOString().slice(0, 10);
const formatDate = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "-";
const formatDateTime = (value: string) => new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
const isOverdue = (task: Task) => task.status !== "Completed" && !!task.dueDate && task.dueDate < today();

const seedMembers: TeamMember[] = [
  { id: "member-1", name: "Aisha Khan", email: "aisha@taskflow.com", role: "Project Manager" },
  { id: "member-2", name: "Rahul Patil", email: "rahul@taskflow.com", role: "Developer" },
  { id: "member-3", name: "Myra Shaikh", email: "myra@taskflow.com", role: "Designer" },
  { id: "member-4", name: "Zoya Ansari", email: "zoya@taskflow.com", role: "Tester" },
];
const seedProjects: Project[] = [
  { id: "PRJ-001", name: "College Event Portal", description: "Manage registrations, events and announcements.", managerId: "member-1", teamIds: ["member-1", "member-2", "member-3"], startDate: "2026-08-01", dueDate: "2026-09-20", priority: "High", status: "In Progress" },
  { id: "PRJ-002", name: "Student Attendance", description: "Simple attendance tracking for students and teachers.", managerId: "member-1", teamIds: ["member-1", "member-2", "member-4"], startDate: "2026-08-15", dueDate: "2026-10-05", priority: "Medium", status: "Planning" },
];
const seedTasks: Task[] = [
  { id: "TSK-001", title: "Create registration screen", description: "Build the registration form and validation.", projectId: "PRJ-001", assignedTo: "member-3", priority: "High", status: "Completed", startDate: "2026-08-02", dueDate: "2026-08-10", createdAt: "2026-08-02T10:00:00" },
  { id: "TSK-002", title: "Build event API", description: "Prepare API structure for event data.", projectId: "PRJ-001", assignedTo: "member-2", priority: "Critical", status: "In Progress", startDate: "2026-08-08", dueDate: "2026-09-08", createdAt: "2026-08-08T11:30:00" },
  { id: "TSK-003", title: "Test registration flow", description: "Test validation and successful submission.", projectId: "PRJ-001", assignedTo: "member-4", priority: "Medium", status: "Review", startDate: "2026-08-18", dueDate: "2026-09-12", createdAt: "2026-08-18T09:15:00" },
  { id: "TSK-004", title: "Attendance wireframe", description: "Create the first attendance page wireframe.", projectId: "PRJ-002", assignedTo: "member-3", priority: "Medium", status: "To Do", startDate: "2026-08-20", dueDate: "2026-09-18", createdAt: "2026-08-20T14:00:00" },
];

function readStorage<T>(key: string, fallback: T): T {
  try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; }
}
function saveStorage(key: string, value: unknown) { localStorage.setItem(key, JSON.stringify(value)); }

function App() {
  const [page, setPage] = useState<Page>(() => readStorage("tf_page", "dashboard"));
  const [user, setUser] = useState<User | null>(() => readStorage<User | null>("tf_user", null));
  const [users, setUsers] = useState<User[]>(() => readStorage("tf_users", [{ id: "user-admin", name: "Admin User", email: "admin@taskflow.com", role: "Admin", password: "123456" }]));
  const [members, setMembers] = useState<TeamMember[]>(() => readStorage("tf_members", seedMembers));
  const [projects, setProjects] = useState<Project[]>(() => readStorage("tf_projects", seedProjects));
  const [tasks, setTasks] = useState<Task[]>(() => readStorage("tf_tasks", seedTasks));
  const [activities, setActivities] = useState<Activity[]>(() => readStorage("tf_activities", []));
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(() => readStorage("tf_selected_project", null));
  const [notice, setNotice] = useState("");

  useEffect(() => saveStorage("tf_users", users), [users]);
  useEffect(() => saveStorage("tf_members", members), [members]);
  useEffect(() => saveStorage("tf_projects", projects), [projects]);
  useEffect(() => saveStorage("tf_tasks", tasks), [tasks]);
  useEffect(() => saveStorage("tf_activities", activities), [activities]);
  useEffect(() => saveStorage("tf_user", user), [user]);
  useEffect(() => saveStorage("tf_page", page), [page]);
  useEffect(() => saveStorage("tf_selected_project", selectedProjectId), [selectedProjectId]);
  useEffect(() => { if (notice) { const t = window.setTimeout(() => setNotice(""), 2500); return () => clearTimeout(t); } }, [notice]);

  const addActivity = (action: string) => {
    setActivities(prev => [{ id: uid("act"), action, user: user?.name || "User", createdAt: new Date().toISOString() }, ...prev].slice(0, 100));
  };
  const go = (next: Page) => { setPage(next); if (next !== "projectDetails") setSelectedProjectId(null); };
  const openProject = (id: string) => { setSelectedProjectId(id); setPage("projectDetails"); };

  const createProject = (data: Omit<Project, "id">) => { const project = { ...data, id: `PRJ-${String(projects.length + 1).padStart(3, "0")}` }; setProjects(p => [...p, project]); addActivity(`Project created: ${project.name}`); setNotice("Project created successfully"); };
  const updateProject = (id: string, data: Omit<Project, "id">) => { setProjects(p => p.map(x => x.id === id ? { ...data, id } : x)); addActivity(`Project updated: ${data.name}`); setNotice("Project updated"); };
  const deleteProject = (id: string) => { const project = projects.find(x => x.id === id); if (!project) return; setProjects(p => p.filter(x => x.id !== id)); setTasks(t => t.filter(x => x.projectId !== id)); addActivity(`Project deleted: ${project.name}`); setNotice("Project deleted"); };
  const createTask = (data: Omit<Task, "id" | "createdAt">) => { const task = { ...data, id: `TSK-${String(tasks.length + 1).padStart(3, "0")}`, createdAt: new Date().toISOString() }; setTasks(t => [...t, task]); addActivity(`Task created: ${task.title}`); setNotice("Task created successfully"); };
  const updateTask = (id: string, data: Omit<Task, "id" | "createdAt">) => { const old = tasks.find(x => x.id === id); setTasks(t => t.map(x => x.id === id ? { ...data, id, createdAt: old?.createdAt || new Date().toISOString() } : x)); if (old && old.status !== data.status) addActivity(`Task status changed: ${data.title} → ${data.status}`); else addActivity(`Task updated: ${data.title}`); setNotice("Task updated"); };
  const deleteTask = (id: string) => { const task = tasks.find(x => x.id === id); if (!task) return; setTasks(t => t.filter(x => x.id !== id)); addActivity(`Task deleted: ${task.title}`); setNotice("Task deleted"); };
  const changeTaskStatus = (id: string, status: TaskStatus) => { const task = tasks.find(x => x.id === id); if (!task || task.status === status) return; setTasks(t => t.map(x => x.id === id ? { ...x, status } : x)); addActivity(`Task status changed: ${task.title} → ${status}`); setNotice(`Task moved to ${status}`); };
  const addMember = (data: Omit<TeamMember, "id">) => { const member = { ...data, id: uid("member") }; setMembers(m => [...m, member]); addActivity(`Team member added: ${member.name}`); setNotice("Team member added"); };
  const updateMember = (id: string, data: Omit<TeamMember, "id">) => { setMembers(m => m.map(x => x.id === id ? { ...data, id } : x)); addActivity(`Team member updated: ${data.name}`); setNotice("Team member updated"); };
  const deleteMember = (id: string) => { const member = members.find(x => x.id === id); if (!member) return; setMembers(m => m.filter(x => x.id !== id)); addActivity(`Team member removed: ${member.name}`); setNotice("Team member removed"); };

  const logout = () => { setUser(null); localStorage.removeItem("tf_user"); setPage("dashboard"); setNotice(""); };

  if (!user) return <Auth users={users} setUsers={setUsers} onLogin={(u) => { setUser(u); setPage("dashboard"); }} />;

  return <div className="app-shell">
    <Sidebar page={page} go={go} logout={logout} />
    <main className="main-content">
      <Header user={user} />
      {notice && <div className="toast">✓ {notice}</div>}
      {page === "dashboard" && <Dashboard projects={projects} tasks={tasks} members={members} activities={activities} openProject={openProject} />}
      {page === "projects" && <Projects projects={projects} tasks={tasks} members={members} user={user} createProject={createProject} updateProject={updateProject} deleteProject={deleteProject} openProject={openProject} />}
      {page === "projectDetails" && selectedProjectId && <ProjectDetails projectId={selectedProjectId} projects={projects} tasks={tasks} members={members} updateTask={updateTask} changeTaskStatus={changeTaskStatus} go={go} />}
      {page === "tasks" && <TasksPage projects={projects} tasks={tasks} members={members} createTask={createTask} updateTask={updateTask} deleteTask={deleteTask} changeTaskStatus={changeTaskStatus} />}
      {page === "calendar" && <CalendarPage tasks={tasks} projects={projects} members={members} />}
      {page === "team" && <TeamPage members={members} tasks={tasks} addMember={addMember} updateMember={updateMember} deleteMember={deleteMember} />}
      {page === "reports" && <Reports projects={projects} tasks={tasks} />}
      {page === "activity" && <ActivityPage activities={activities} />}
      {page === "settings" && <Settings user={user} logout={logout} />}
    </main>
  </div>;
}

function Auth({ users, setUsers, onLogin }: { users: User[]; setUsers: React.Dispatch<React.SetStateAction<User[]>>; onLogin: (user: User) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState<Role>("Member"); const [confirm, setConfirm] = useState(""); const [error, setError] = useState("");
  const submit = (e: FormEvent) => { e.preventDefault(); setError("");
    if (mode === "login") { const found = users.find(u => u.email.toLowerCase() === email.toLowerCase() && u.password === password); if (!found) { setError("Invalid email or password. Try admin@taskflow.com / 123456."); return; } onLogin(found); return; }
    if (!name.trim() || !email.includes("@") || password.length < 6 || password !== confirm) { setError("Please enter valid details and make sure both passwords match."); return; }
    if (users.some(u => u.email.toLowerCase() === email.toLowerCase())) { setError("An account with this email already exists."); return; }
    const newUser = { id: uid("user"), name: name.trim(), email: email.trim(), role, password }; setUsers(u => [...u, newUser]); setEmail(newUser.email); setPassword(""); setConfirm(""); setName(""); setMode("login"); setError("Account created. Please log in.");
  };
  return <div className="auth-page"><div className="auth-container"><section className="auth-left"><div className="brand"><span className="brand-icon">✓</span><b>Task<span>Flow</span></b></div><div className="auth-copy"><h1>Plan. Track. <span>Complete.</span></h1><p>A simple project management workspace for teams to organize tasks and track progress.</p><div className="feature-list"><div>✓ <b>Track projects</b><small>Keep every project status in one place.</small></div><div>✓ <b>Manage tasks</b><small>Create, assign and update work easily.</small></div><div>✓ <b>Work together</b><small>Manage team members and activity.</small></div></div></div><div className="mini-kanban"><div><b>TO DO</b><i/><i/></div><div><b>IN PROGRESS</b><i className="purple"/><i/></div><div><b>COMPLETED</b><i className="dark"/><i className="purple"/></div></div></section><section className="auth-right"><form className="auth-form" onSubmit={submit}><div className="form-heading"><h2>{mode === "login" ? "Welcome back" : "Create account"}</h2><p>{mode === "login" ? "Sign in to continue to TaskFlow." : "Create your TaskFlow account."}</p></div>{mode === "signup" && <Field label="Full name"><input value={name} onChange={e => setName(e.target.value)} placeholder="Enter your name" /></Field>}<Field label="Email"><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></Field><Field label="Password"><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter password" /></Field>{mode === "signup" && <><Field label="Confirm password"><input type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Confirm password" /></Field><Field label="Role"><select value={role} onChange={e => setRole(e.target.value as Role)}>{ROLES.map(r => <option key={r}>{r}</option>)}</select></Field></>}{error && <div className="form-error">{error}</div>}<button className="primary-btn" type="submit">{mode === "login" ? "Login" : "Create Account"}</button><p className="switch-auth">{mode === "login" ? "Don't have an account?" : "Already have an account?"} <button type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Sign up" : "Login"}</button></p>{mode === "login" && <p className="demo-login">Demo: admin@taskflow.com · 123456</p>}</form></section></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="field"><label>{label}</label>{children}</div>; }

function Sidebar({ page, go, logout }: { page: Page; go: (p: Page) => void; logout: () => void }) {
  const items: [Page, string, string][] = [["dashboard", "▣", "Dashboard"], ["projects", "▤", "Projects"], ["tasks", "✓", "Tasks"], ["calendar", "◫", "Calendar"], ["team", "♟", "Team"], ["reports", "▥", "Reports"], ["activity", "◷", "Activity"], ["settings", "⚙", "Settings"]];
  return <aside className="sidebar"><div className="sidebar-brand"><span>✓</span><b>Task<span>Flow</span></b></div><nav>{items.map(([p, icon, label]) => <button key={p} className={page === p || (page === "projectDetails" && p === "projects") ? "active" : ""} onClick={() => go(p)}><strong>{icon}</strong>{label}</button>)}</nav><button className="logout-side" onClick={logout}>↪ Logout</button></aside>;
}
function Header({ user }: { user: User }) { return <header className="topbar"><div><span className="mobile-title">TaskFlow</span></div><div className="top-user"><button className="notification">♢</button><div className="avatar">{user.name.charAt(0).toUpperCase()}</div><div><b>{user.name}</b><small>{user.role}</small></div></div></header>; }

function PageTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="page-title"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
function StatCard({ label, value, icon }: { label: string; value: number; icon: string }) { return <div className="stat-card"><span className="stat-icon">{icon}</span><div><p>{label}</p><h2>{value}</h2></div></div>; }
function StatusBadge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>; }
function PriorityBadge({ value }: { value: Priority }) { return <span className={`priority ${value.toLowerCase()}`}>{value}</span>; }

function projectProgress(projectId: string, tasks: Task[]) { const list = tasks.filter(t => t.projectId === projectId); return list.length ? Math.round(list.filter(t => t.status === "Completed").length / list.length * 100) : 0; }
function Dashboard({ projects, tasks, members, activities, openProject }: { projects: Project[]; tasks: Task[]; members: TeamMember[]; activities: Activity[]; openProject: (id: string) => void }) {
  const active = projects.filter(p => p.status === "In Progress").length; const completed = projects.filter(p => p.status === "Completed").length; const overdue = tasks.filter(isOverdue).length;
  return <><PageTitle title="Dashboard" subtitle={`Welcome back. Today is ${formatDate(today())}.`} /><div className="stats-grid"><StatCard label="Total Projects" value={projects.length} icon="▤"/><StatCard label="Active Projects" value={active} icon="◉"/><StatCard label="Completed Projects" value={completed} icon="✓"/><StatCard label="Total Tasks" value={tasks.length} icon="☷"/><StatCard label="To Do" value={tasks.filter(t=>t.status==="To Do").length} icon="○"/><StatCard label="In Progress" value={tasks.filter(t=>t.status==="In Progress").length} icon="◐"/><StatCard label="Completed Tasks" value={tasks.filter(t=>t.status==="Completed").length} icon="✓"/><StatCard label="Overdue Tasks" value={overdue} icon="!"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>Project Progress</h2><span>{projects.length} projects</span></div>{projects.length === 0 ? <Empty text="No projects yet."/> : <div className="progress-list">{projects.map(p => <button className="progress-row" key={p.id} onClick={() => openProject(p.id)}><div className="row-main"><div><b>{p.name}</b><small>{members.find(m=>m.id===p.managerId)?.name || "No manager"} · {p.status}</small></div><strong>{projectProgress(p.id,tasks)}%</strong></div><div className="progress-track"><span style={{width: `${projectProgress(p.id,tasks)}%`}}/></div><div className="row-meta"><span>{tasks.filter(t=>t.projectId===p.id && t.status==="Completed").length}/{tasks.filter(t=>t.projectId===p.id).length} tasks completed</span><span>Due {formatDate(p.dueDate)}</span></div></button>)}</div>}</section><section className="panel"><div className="panel-heading"><h2>Recent Activity</h2><span>{activities.length}</span></div>{activities.length === 0 ? <Empty text="No activity yet. Create a project or task to get started."/> : <ActivityList activities={activities.slice(0,7)}/>}</section></div></>;
}
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function ActivityList({ activities }: { activities: Activity[] }) { return <div className="activity-list">{activities.map(a => <div className="activity-item" key={a.id}><span className="activity-dot">•</span><div><b>{a.action}</b><small>{a.user} · {formatDateTime(a.createdAt)}</small></div></div>)}</div>; }

function Projects({ projects, tasks, members, user, createProject, updateProject, deleteProject, openProject }: { projects: Project[]; tasks: Task[]; members: TeamMember[]; user: User; createProject: (x: Omit<Project,"id">)=>void; updateProject:(id:string,x:Omit<Project,"id">)=>void; deleteProject:(id:string)=>void; openProject:(id:string)=>void }) {
  const [modal, setModal] = useState<"create"|Project|null>(null); const [search,setSearch]=useState("");
  const filtered=projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||p.id.toLowerCase().includes(search.toLowerCase()));
  const managerOptions = members.length ? members : [{id:"current",name:user.name,email:user.email,role:user.role} as TeamMember];
  return <><PageTitle title="Projects" subtitle="Create and track all your projects." action={<button className="primary-btn small" onClick={()=>setModal("create")}>+ Create Project</button>}/><div className="toolbar"><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects..."/><span>{filtered.length} projects</span></div><div className="project-grid">{filtered.map(p=><ProjectCard key={p.id} project={p} tasks={tasks} members={members} onView={()=>openProject(p.id)} onEdit={()=>setModal(p)} onDelete={()=>window.confirm(`Delete ${p.name}?`)&&deleteProject(p.id)}/>)}</div>{filtered.length===0&&<Empty text="No matching projects."/>}{modal&&<ProjectModal initial={modal === "create" ? null : modal} members={managerOptions} onClose={()=>setModal(null)} onSave={data=>{modal === "create" ? createProject(data) : updateProject((modal as Project).id,data); setModal(null)}}/>}</>;
}
function ProjectCard({ project, tasks, members, onView, onEdit, onDelete }: { project: Project; tasks: Task[]; members: TeamMember[]; onView:()=>void; onEdit:()=>void; onDelete:()=>void }) { const p=projectProgress(project.id,tasks); return <div className="project-card"><div className="card-top"><span className="project-id">{project.id}</span><StatusBadge value={project.status}/></div><h3>{project.name}</h3><p>{project.description || "No description"}</p><div className="card-info"><span>Manager <b>{members.find(m=>m.id===project.managerId)?.name||"-"}</b></span><span>Due <b>{formatDate(project.dueDate)}</b></span></div><div className="card-info"><PriorityBadge value={project.priority}/><span>{tasks.filter(t=>t.projectId===project.id).length} tasks</span></div><div className="progress-track"><span style={{width:`${p}%`}}/></div><div className="card-progress"><b>{p}% complete</b><span>{tasks.filter(t=>t.projectId===project.id&&t.status==="Completed").length} completed</span></div><div className="card-actions"><button onClick={onView}>View Details</button><button onClick={onEdit}>Edit</button><button className="danger-text" onClick={onDelete}>Delete</button></div></div>; }

function ProjectModal({ initial, members, onClose, onSave }: { initial: Project|null; members: TeamMember[]; onClose:()=>void; onSave:(x:Omit<Project,"id">)=>void }) { const [name,setName]=useState(initial?.name||""); const [description,setDescription]=useState(initial?.description||""); const [managerId,setManagerId]=useState(initial?.managerId||members[0]?.id||""); const [teamIds,setTeamIds]=useState<string[]>(initial?.teamIds||members.slice(0,2).map(m=>m.id)); const [startDate,setStartDate]=useState(initial?.startDate||today()); const [dueDate,setDueDate]=useState(initial?.dueDate||""); const [priority,setPriority]=useState<Priority>(initial?.priority||"Medium"); const [status,setStatus]=useState<ProjectStatus>(initial?.status||"Not Started"); const submit=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!dueDate)return;onSave({name,description,managerId,teamIds,startDate,dueDate,priority,status});}; return <Modal title={initial?"Edit Project":"Create Project"} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Project name"><input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Manager"><select value={managerId} onChange={e=>setManagerId(e.target.value)}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Start date"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field><Field label="Due date"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></Field><Field label="Priority"><select value={priority} onChange={e=>setPriority(e.target.value as Priority)}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value as ProjectStatus)}>{PROJECT_STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field><div className="full-field"><Field label="Description"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></Field></div><div className="full-field"><label>Team members</label><div className="check-grid">{members.map(m=><label key={m.id}><input type="checkbox" checked={teamIds.includes(m.id)} onChange={e=>setTeamIds(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/>{m.name}</label>)}</div></div></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-btn" type="submit">{initial?"Save Changes":"Create Project"}</button></div></form></Modal>; }

function ProjectDetails({ projectId, projects, tasks, members, updateTask, changeTaskStatus, go }: { projectId:string; projects:Project[]; tasks:Task[]; members:TeamMember[]; updateTask:(id:string,x:Omit<Task,"id"|"createdAt">)=>void; changeTaskStatus:(id:string,s:TaskStatus)=>void; go:(p:Page)=>void }) { const project=projects.find(p=>p.id===projectId); const list=tasks.filter(t=>t.projectId===projectId); if(!project)return <Empty text="Project not found."/>; const p=projectProgress(project.id,tasks); const [modal,setModal]=useState<Task|null>(null); return <><button className="back-btn" onClick={()=>go("projects")}>← Back to Projects</button><PageTitle title={project.name} subtitle={project.description}/><div className="detail-head"><div><span className="project-id">{project.id}</span><StatusBadge value={project.status}/><PriorityBadge value={project.priority}/></div><div className="detail-meta"><span>Manager: <b>{members.find(m=>m.id===project.managerId)?.name||"-"}</b></span><span>{formatDate(project.startDate)} → {formatDate(project.dueDate)}</span></div></div><div className="detail-stats"><StatCard label="Total Tasks" value={list.length} icon="☷"/><StatCard label="To Do" value={list.filter(t=>t.status==="To Do").length} icon="○"/><StatCard label="In Progress" value={list.filter(t=>t.status==="In Progress").length} icon="◐"/><StatCard label="Review" value={list.filter(t=>t.status==="Review").length} icon="◇"/><StatCard label="Completed" value={list.filter(t=>t.status==="Completed").length} icon="✓"/><StatCard label="Overdue" value={list.filter(isOverdue).length} icon="!"/></div><section className="panel"><div className="panel-heading"><h2>Project Progress</h2><b>{p}%</b></div><div className="big-progress"><span style={{width:`${p}%`}}/></div></section><section className="panel"><div className="panel-heading"><h2>Kanban Board</h2><button className="secondary-btn" onClick={()=>go("tasks")}>Manage Tasks</button></div><div className="kanban-board">{TASK_STATUSES.map(status=><div className="kanban-column" key={status}><div className="column-title"><b>{status}</b><span>{list.filter(t=>t.status===status).length}</span></div>{list.filter(t=>t.status===status).map(t=><TaskCard key={t.id} task={t} members={members} onEdit={()=>setModal(t)} onStatus={s=>changeTaskStatus(t.id,s)}/>) }{list.filter(t=>t.status===status).length===0&&<div className="column-empty">No tasks</div>}</div>)}</div></section>{modal&&<TaskModal initial={modal} projects={projects} members={members} onClose={()=>setModal(null)} onSave={data=>{updateTask(modal.id,data);setModal(null)}}/>}</>; }
function TaskCard({task,members,onEdit,onStatus}:{task:Task;members:TeamMember[];onEdit:()=>void;onStatus:(s:TaskStatus)=>void}) { return <div className="task-card"><div className="task-card-title"><b>{task.title}</b><button onClick={onEdit}>⋮</button></div><p>{task.description}</p><div className="task-tags"><PriorityBadge value={task.priority}/>{isOverdue(task)&&<span className="overdue">Overdue</span>}</div><small>👤 {members.find(m=>m.id===task.assignedTo)?.name||"Unassigned"}</small><small>Due {formatDate(task.dueDate)}</small><select value={task.status} onChange={e=>onStatus(e.target.value as TaskStatus)}>{TASK_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>; }

function TasksPage({projects,tasks,members,createTask,updateTask,deleteTask,changeTaskStatus}:{projects:Project[];tasks:Task[];members:TeamMember[];createTask:(x:Omit<Task,"id"|"createdAt">)=>void;updateTask:(id:string,x:Omit<Task,"id"|"createdAt">)=>void;deleteTask:(id:string)=>void;changeTaskStatus:(id:string,s:TaskStatus)=>void}) { const [modal,setModal]=useState<"create"|Task|null>(null); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("All"); const filtered=tasks.filter(t=>(filter==="All"||(filter==="Overdue"?isOverdue(t):t.status===filter))&&(t.title+" "+(projects.find(p=>p.id===t.projectId)?.name||"")+" "+(members.find(m=>m.id===t.assignedTo)?.name||"")).toLowerCase().includes(search.toLowerCase())); return <><PageTitle title="Tasks" subtitle="Manage work across all projects." action={<button className="primary-btn small" onClick={()=>setModal("create")}>+ Create Task</button>}/><div className="toolbar"><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search task, project or member..."/><div className="filter-row">{["All",...TASK_STATUSES,"Overdue"].map(f=><button key={f} className={filter===f?"filter active":"filter"} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>Task</th><th>Project</th><th>Assigned To</th><th>Priority</th><th>Status</th><th>Due Date</th><th>Actions</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td><b>{t.title}</b><small>{t.description}</small></td><td>{projects.find(p=>p.id===t.projectId)?.name||"-"}</td><td>{members.find(m=>m.id===t.assignedTo)?.name||"-"}</td><td><PriorityBadge value={t.priority}/></td><td><select className="inline-select" value={t.status} onChange={e=>changeTaskStatus(t.id,e.target.value as TaskStatus)}>{TASK_STATUSES.map(s=><option key={s}>{s}</option>)}</select></td><td className={isOverdue(t)?"text-overdue":""}>{formatDate(t.dueDate)}</td><td><button className="table-btn" onClick={()=>setModal(t)}>Edit</button><button className="table-btn danger-text" onClick={()=>window.confirm(`Delete ${t.title}?`)&&deleteTask(t.id)}>Delete</button></td></tr>)}</tbody></table></div>{filtered.length===0&&<Empty text="No tasks match your filters."/>}{modal&&<TaskModal initial={modal === "create" ? null : modal} projects={projects} members={members} onClose={()=>setModal(null)} onSave={data=>{modal === "create" ? createTask(data) : updateTask((modal as Task).id,data);setModal(null)}}/>}</>; }

function TaskModal({initial,projects,members,onClose,onSave}:{initial:Task|null;projects:Project[];members:TeamMember[];onClose:()=>void;onSave:(x:Omit<Task,"id"|"createdAt">)=>void}) { const [title,setTitle]=useState(initial?.title||"");const [description,setDescription]=useState(initial?.description||"");const [projectId,setProjectId]=useState(initial?.projectId||projects[0]?.id||"");const [assignedTo,setAssignedTo]=useState(initial?.assignedTo||members[0]?.id||"");const [priority,setPriority]=useState<Priority>(initial?.priority||"Medium");const [status,setStatus]=useState<TaskStatus>(initial?.status||"To Do");const [startDate,setStartDate]=useState(initial?.startDate||today());const [dueDate,setDueDate]=useState(initial?.dueDate||"");const submit=(e:FormEvent)=>{e.preventDefault();if(!title.trim()||!projectId||!dueDate)return;onSave({title,description,projectId,assignedTo,priority,status,startDate,dueDate});};return <Modal title={initial?"Edit Task":"Create Task"} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Task title"><input value={title} onChange={e=>setTitle(e.target.value)} required/></Field><Field label="Project"><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Assigned member"><select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Priority"><select value={priority} onChange={e=>setPriority(e.target.value as Priority)}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value as TaskStatus)}>{TASK_STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Start date"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field><Field label="Due date"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></Field><div className="full-field"><Field label="Description"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></Field></div></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-btn" type="submit">{initial?"Save Changes":"Create Task"}</button></div></form></Modal>; }

function CalendarPage({tasks,projects,members}:{tasks:Task[];projects:Project[];members:TeamMember[]}) { const [month,setMonth]=useState(new Date()); const year=month.getFullYear();const m=month.getMonth();const days=new Date(year,m+1,0).getDate();const first=new Date(year,m,1).getDay();const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);const tasksByDay=(d:number)=>tasks.filter(t=>{if(!t.dueDate)return false;const x=new Date(`${t.dueDate}T00:00:00`);return x.getFullYear()===year&&x.getMonth()===m&&x.getDate()===d;});return <><PageTitle title="Calendar" subtitle="View tasks by their due dates."/><section className="panel calendar-panel"><div className="calendar-head"><button onClick={()=>setMonth(new Date(year,m-1,1))}>←</button><h2>{month.toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</h2><button onClick={()=>setMonth(new Date(year,m+1,1))}>→</button></div><div className="calendar-grid weekday">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><b key={d}>{d}</b>)}</div><div className="calendar-grid">{cells.map((d,i)=><div className="calendar-day" key={i}>{d&&<><strong>{d}</strong>{tasksByDay(d).map(t=><div className={`calendar-task ${isOverdue(t)?"calendar-overdue":""}`} key={t.id} title={t.title}>{t.title}<small>{projects.find(p=>p.id===t.projectId)?.name||""} · {members.find(m=>m.id===t.assignedTo)?.name||"-"}</small></div>)}</>}</div>)}</div></section></>; }

function TeamPage({members,tasks,addMember,updateMember,deleteMember}:{members:TeamMember[];tasks:Task[];addMember:(x:Omit<TeamMember,"id">)=>void;updateMember:(id:string,x:Omit<TeamMember,"id">)=>void;deleteMember:(id:string)=>void}) { const [modal,setModal]=useState<"create"|TeamMember|null>(null);return <><PageTitle title="Team" subtitle="Manage project team members." action={<button className="primary-btn small" onClick={()=>setModal("create")}>+ Add Member</button>}/><div className="team-grid">{members.map(m=>{const assigned=tasks.filter(t=>t.assignedTo===m.id);return <div className="member-card" key={m.id}><div className="member-avatar">{m.name.charAt(0)}</div><h3>{m.name}</h3><StatusBadge value={m.role}/><p>{m.email}</p><div className="member-stats"><span><b>{assigned.length}</b>Assigned</span><span><b>{assigned.filter(t=>t.status==="Completed").length}</b>Completed</span><span><b>{assigned.filter(t=>t.status!=="Completed").length}</b>Active</span></div><div className="card-actions"><button onClick={()=>setModal(m)}>Edit</button><button className="danger-text" onClick={()=>window.confirm(`Delete ${m.name}?`)&&deleteMember(m.id)}>Delete</button></div></div>})}</div>{members.length===0&&<Empty text="No team members yet."/>}{modal&&<MemberModal initial={modal === "create" ? null : modal} onClose={()=>setModal(null)} onSave={data=>{modal === "create"?addMember(data):updateMember((modal as TeamMember).id,data);setModal(null)}}/>}</>; }
function MemberModal({initial,onClose,onSave}:{initial:TeamMember|null;onClose:()=>void;onSave:(x:Omit<TeamMember,"id">)=>void}){const[name,setName]=useState(initial?.name||"");const[email,setEmail]=useState(initial?.email||"");const[role,setRole]=useState<Role>(initial?.role||"Member");return <Modal title={initial?"Edit Member":"Add Member"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(name&&email)onSave({name,email,role})}}><Field label="Name"><input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Role"><select value={role} onChange={e=>setRole(e.target.value as Role)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></Field><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-btn" type="submit">Save</button></div></form></Modal>}

function Reports({projects,tasks}:{projects:Project[];tasks:Task[]}) { const projectStatus=PROJECT_STATUSES.map(s=>[s,projects.filter(p=>p.status===s).length] as const);const taskStatus=TASK_STATUSES.map(s=>[s,tasks.filter(t=>t.status===s).length] as const);const maxP=Math.max(1,...projectStatus.map(x=>x[1]));const maxT=Math.max(1,...taskStatus.map(x=>x[1]));return <><PageTitle title="Reports" subtitle="Simple live statistics from your projects and tasks."/><div className="report-grid"><section className="panel"><div className="panel-heading"><h2>Project Status Summary</h2></div>{projectStatus.map(([s,n])=><div className="bar-row" key={s}><span>{s}</span><div><i style={{width:`${n/maxP*100}%`}}/></div><b>{n}</b></div>)}</section><section className="panel"><div className="panel-heading"><h2>Task Status Summary</h2></div>{taskStatus.map(([s,n])=><div className="bar-row" key={s}><span>{s}</span><div><i style={{width:`${n/maxT*100}%`}}/></div><b>{n}</b></div>)}</section></div><div className="stats-grid"><StatCard label="Total Projects" value={projects.length} icon="▤"/><StatCard label="Completed Projects" value={projects.filter(p=>p.status==="Completed").length} icon="✓"/><StatCard label="Active Projects" value={projects.filter(p=>p.status==="In Progress").length} icon="◉"/><StatCard label="Total Tasks" value={tasks.length} icon="☷"/><StatCard label="Completed Tasks" value={tasks.filter(t=>t.status==="Completed").length} icon="✓"/><StatCard label="Overdue Tasks" value={tasks.filter(isOverdue).length} icon="!"/></div></>; }
function ActivityPage({activities}:{activities:Activity[]}){return <><PageTitle title="Activity" subtitle="A timeline of recent changes in TaskFlow."/>{activities.length?<section className="panel"><ActivityList activities={activities}/></section>:<Empty text="No activity yet."/>}</>}
function Settings({user,logout}:{user:User;logout:()=>void}){const[notifications,setNotifications]=useState(()=>readStorage("tf_notifications",true));const toggle=(v:boolean)=>{setNotifications(v);saveStorage("tf_notifications",v)};return <><PageTitle title="Settings" subtitle="Manage your profile and application preferences."/><div className="settings-grid"><section className="panel"><h2>Profile</h2><div className="profile-large"><div className="avatar big">{user.name.charAt(0)}</div><div><h3>{user.name}</h3><p>{user.email}</p><StatusBadge value={user.role}/></div></div></section><section className="panel"><h2>Application Settings</h2><label className="setting-row"><span><b>Notifications</b><small>Show task and activity notifications.</small></span><input type="checkbox" checked={notifications} onChange={e=>toggle(e.target.checked)}/></label></section><section className="panel"><h2>Account</h2><button className="danger-btn" onClick={logout}>Logout</button></section></div></>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-heading"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}

export default App;
